import { useState } from "react"

function AIAnalyzer() {
    const [jobDescription, setJobDescription] = useState("")
    const [result, setResult] = useState(null)
    const [loading, setLoading] = useState(false)
    const [error, setError] = useState("")

    const handleAnalyze = async () => {
        if (!jobDescription.trim()) {
            setError("Please paste a job description first")
            return
        }
        setError("")
        setLoading(true)
        setResult(null)
        try {
            const response = await fetch("http://localhost:8000/analyze", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ description: jobDescription })
            })
            const data = await response.json()
            if (!response.ok) {
                setError(data.detail || "Analysis failed")
                return
            }
            setResult(data)
        } catch (err) {
            setError("Cannot connect to server. Is backend running?")
        } finally {
            setLoading(false)
        }
    }

    return (
        <div className="max-w-3xl mx-auto">
            <div className="mb-6">
                <h2 className="text-2xl font-bold text-gray-800">AI Job Analyzer</h2>
                <p className="text-gray-500 text-sm mt-1">
                    Paste a job description → get skill gaps and likely interview questions
                </p>
            </div>
            <div className="bg-white rounded-xl border border-gray-200 p-6 mb-4">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                    Paste Job Description
                </label>
                <textarea
                    value={jobDescription}
                    onChange={(e) => setJobDescription(e.target.value)}
                    placeholder="Paste the full job description here..."
                    rows={8}
                    className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
                />
                {error && (
                    <p className="mt-2 text-sm text-red-500">{error}</p>
                )}
                <button
                    onClick={handleAnalyze}
                    disabled={loading}
                    className="mt-4 w-full bg-blue-600 text-white py-2.5 rounded-lg text-sm font-medium hover:bg-blue-700 disabled:opacity-50"
                >
                    {loading ? "Analyzing with AI..." : "Analyze Job Description"}
                </button>
            </div>

            {result && (
                <div className="space-y-4">
                    <div className="bg-white rounded-xl border border-gray-200 p-6">
                        <h3 className="font-semibold text-gray-800 mb-3">Key Skills Required</h3>
                        <div className="flex flex-wrap gap-2">
                            {result.skills.map((skill, i) => (
                                <span key={i} className="bg-blue-50 text-blue-700 px-3 py-1 rounded-full text-sm font-medium">
                                    {skill}
                                </span>
                            ))}
                        </div>
                    </div>
                    <div className="bg-white rounded-xl border border-orange-200 p-6">
                        <h3 className="font-semibold text-gray-800 mb-1">Likely Interview Questions</h3>
                        <p className="text-xs text-gray-400 mb-4">Generated by AI based on this job description</p>
                        <div className="space-y-3">
                            {result.questions.map((q, i) => (
                                <div key={i} className="flex gap-3 p-3 bg-orange-50 rounded-lg">
                                    <span className="text-orange-500 font-bold text-sm min-w-[20px]">{i + 1}.</span>
                                    <p className="text-sm text-gray-700">{q}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                    {result.tip && (
                        <div className="bg-green-50 border border-green-200 rounded-xl p-4">
                            <p className="text-sm text-green-700">
                                <span className="font-medium">Pro tip: </span>{result.tip}
                            </p>
                        </div>
                    )}
                </div>
            )}
        </div>
    )
}

export default AIAnalyzer